const String domain = "https://dash.aquan.website";

const Map<String, dynamic> auth = {
  "login": "$domain/api/auth/login",
  "register": "$domain/api/auth/register",
  "check": "$domain/api/auth/check",
  "password": {
    "reset": "$domain/api/auth/reset-password",
  },
  "confirm-email": "$domain/api/v1/user/verify",
  "send-confirm-email": "$domain/api/v1/user/verify",
  "send-code-to-email": "$domain/api/resendcode",
  "settings": "$domain/api/settings",
  "tasks": "$domain/api/tasks",
  "task": "$domain/api/tasks/",
  "referals": "$domain/api/referals",
  "user": "$domain/api/user",
  "change-password": "$domain/api/user/change-password",
  "plans": "$domain/api/plans",
  "wallets": "$domain/api/wallets",
  "transactions": "$domain/api/transactions",
  "deposits": "$domain/api/deposits",
  "deposit": "$domain/api/deposits/create",
  "currencies": "$domain/api/currencies",
  "transfer": "$domain/api/currencies/transfer",
  "withdraws": "$domain/api/withdraws",
  "withdraw": "$domain/api/withdraws/create",
  "dashboard": "$domain/api/dashboard",
  "support": "$domain/api/support",
  "account": "$domain/api/account/",
  "notifications": "$domain/api/notifications",
  "deposits-and-withdraws": "$domain/api/invoices/withdraws-deposits",
  "auth-google": "$domain/api/auth/login/google",
  "auth-google-complete": "$domain/api/auth/login/google/complete",
  "debug": "$domain/api/debug",
};
