name: aquan
description: "aquan"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  ai_barcode_scanner: ^5.1.1
  animated_bottom_navigation_bar: ^1.3.3
  animated_splash_screen: ^1.3.0
  another_flushbar: ^1.12.30
  auto_route: ^9.2.2
  barcode_widget: ^2.0.4
  bubble: ^1.2.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  currency_text_input_formatter: ^2.2.4
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  data_table_2: ^2.5.12
  device_preview: ^1.2.0
  dio: ^5.7.0
  drop_down_list: ^0.0.7
  dropdown_model_list: ^2.1.2
  easy_sidemenu: ^0.6.0
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  file_picker: ^6.1.1
  flutter_bloc: ^8.1.4
  flutter_clean_architecture: ^6.0.1
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^8.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  local_auth: ^2.2.0
  logger: ^2.4.0
  motion_toast: ^2.8.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  stream_chat_flutter_core: ^7.2.0
  url_launcher: ^6.2.5
  video_player: ^2.9.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^5.5.1
  flutter_otp_text_field: ^1.4.0+2

dev_dependencies:
  bloc_test: ^9.1.0
  mockito: ^5.3.2 
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  package_rename: ^1.7.1
  retrofit_generator: '>=8.0.0 <10.0.0'
  freezed: ^2.5.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
flutter_native_splash:
  color: "#FFFFFF"
  android_gravity: fill
  android_12:
    image: assets/icon/AppColors.white.png
  android: true
  ios: true
  web: true
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icon/
