// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBJzNWXsV-UPdSYod2eagdHvS3V_6AEYW4',
//     appId: '1:468746216391:web:4cea5452411bc488306fe2',
//     messagingSenderId: '468746216391',
//     projectId: 'aquan-c8534',
//     authDomain: 'aquan-c8534.firebaseapp.com',
//     storageBucket: 'aquan-c8534.firebasestorage.app',
//     measurementId: 'G-0RSEN21NEH',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA8O57eAtziO8vuXsAD7qQUH7p0MfxpiLw',
//     appId: '1:468746216391:android:5eb07a2c5d05089e306fe2',
//     messagingSenderId: '468746216391',
//     projectId: 'aquan-c8534',
//     storageBucket: 'aquan-c8534.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDp4OcRqCKP8z4eFWAj3cQAULQ_IAPAxC0',
//     appId: '1:468746216391:ios:073d74df9b800c2f306fe2',
//     messagingSenderId: '468746216391',
//     projectId: 'aquan-c8534',
//     storageBucket: 'aquan-c8534.firebasestorage.app',
//     iosBundleId: 'com.aquan.app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDp4OcRqCKP8z4eFWAj3cQAULQ_IAPAxC0',
//     appId: '1:468746216391:ios:073d74df9b800c2f306fe2',
//     messagingSenderId: '468746216391',
//     projectId: 'aquan-c8534',
//     storageBucket: 'aquan-c8534.firebasestorage.app',
//     iosBundleId: 'com.aquan.app',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBJzNWXsV-UPdSYod2eagdHvS3V_6AEYW4',
//     appId: '1:468746216391:web:76cdd5c394942c21306fe2',
//     messagingSenderId: '468746216391',
//     projectId: 'aquan-c8534',
//     authDomain: 'aquan-c8534.firebaseapp.com',
//     storageBucket: 'aquan-c8534.firebasestorage.app',
//     measurementId: 'G-C1SY8RDEPE',
//   );
// }
