// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRoVPV3sCSbRq-08v1rBvnSVg7BNMXAQ',
    appId: '1:19118574319:web:1f05a4fcf822a742eb291a',
    messagingSenderId: '19118574319',
    projectId: 'aquan-dev',
    authDomain: 'aquan-dev.firebaseapp.com',
    storageBucket: 'aquan-dev.firebasestorage.app',
    measurementId: 'G-4ZC76GWQH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAktff8ZOyRmO2VtaJzGTaDxn20hmQ07b4',
    appId: '1:19118574319:android:1bdb6ba41686756deb291a',
    messagingSenderId: '19118574319',
    projectId: 'aquan-dev',
    storageBucket: 'aquan-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53iUt4Hm3ojD0P-1AA42SytdUtGRtZxI',
    appId: '1:19118574319:ios:085e585d27c3acd4eb291a',
    messagingSenderId: '19118574319',
    projectId: 'aquan-dev',
    storageBucket: 'aquan-dev.firebasestorage.app',
    iosBundleId: 'com.aquan.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53iUt4Hm3ojD0P-1AA42SytdUtGRtZxI',
    appId: '1:19118574319:ios:085e585d27c3acd4eb291a',
    messagingSenderId: '19118574319',
    projectId: 'aquan-dev',
    storageBucket: 'aquan-dev.firebasestorage.app',
    iosBundleId: 'com.aquan.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGRoVPV3sCSbRq-08v1rBvnSVg7BNMXAQ',
    appId: '1:19118574319:web:9cd2ae9778f3c37ceb291a',
    messagingSenderId: '19118574319',
    projectId: 'aquan-dev',
    authDomain: 'aquan-dev.firebaseapp.com',
    storageBucket: 'aquan-dev.firebasestorage.app',
    measurementId: 'G-LZX7VY9WP1',
  );

}