name: Build and Distribute Flutter APKs
on:
  # workflow_dispatch:
    push:
      branches:
        - dev 
         # استبدل 'main' بالفرع الذي ترغب في تفعيله
jobs:
  build:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
      #! 1. تفعيل الكاش
      - name: Checkout code
        uses: actions/checkout@v2
      #! 2. إعداد JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      #! 3. تفعيل الكاش لتثبيت Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
      #!
      - name: Cache Pub Packages
        uses: actions/cache@v2
        with:
            path: ~/.pub-cache
            key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml') }}    
      #! 4. تثبيت Flutter
      - name: Install Flutter
        run: |
          if [ ! -d "$HOME/.flutter/bin" ]; then
            git clone https://github.com/flutter/flutter.git -b stable $HOME/.flutter
          fi
          echo "$HOME/.flutter/bin" >> $GITHUB_PATH
      #! 5. إعداد Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.24.4'
      #! 6. تحميل التبعيات
      - name: Flutter pub get
        run: flutter pub get
      #! 7. بناء النسخ المتنوعة للتطبيق
      - name: Build APKs
        run: |
          # flutter build apk --release
          # flutter build appbundle --release
          # flutter build apk --profile                     
          # flutter build apk --target-platform android-arm,android-arm64,android-x64
          flutter build apk --split-per-abi
      # ! 8. توزيع نسخ التطبيق 
      # #! app-release.apk
      # - name: Upload Release APK to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: app-release.apk
      #     file: build/app/outputs/flutter-apk/app-release.apk
      #     debug: false
      #     releaseNotes: "app-release.apk"
      #! app-armeabi-v7a-release.apk
      - name: Upload app-armeabi-v7a-release.apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-armeabi-v7a-release.apk                           
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          releaseNotes: "app-armeabi-v7a-release.apk"
      # #! app-arm64-v8a-release.apk
      # - name: Upload app-arm64-v8a-release.apk to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: app-arm64-v8a-release.apk                   
      #     file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      #     releaseNotes: "app-arm64-v8a-release.apk"
      # #! app-profile.apk  
      # - name: Upload app-profile.apk to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: app-profile.apk
      #     file: build/app/outputs/flutter-apk/app-profile.apk
      #     debug: false
      #     releaseNotes: "app-profile.apk"
      # #! app-x86_64-release.apk
      # - name: Upload app-x86_64-release.apk to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: app-x86_64-release.apk
      #     file: build/app/outputs/flutter-apk/app-x86_64-release.apk          
      #     releaseNotes: "app-x86_64-release.apk"