name: test
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Install Flutter
        run: |
          if [ ! -d "$HOME/.flutter/bin" ]; then
            git clone https://github.com/flutter/flutter.git -b stable $HOME/.flutter
          fi
          echo "$HOME/.flutter/bin" >> $GITHUB_PATH

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.24.4'

      - name: Cache Pub Packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml') }}

      - name: Flutter pub get
        run: flutter pub get

      - name: Install Shorebird
        run: dart pub global activate shorebird

      - name: Add Dart pub-cache to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Build APKs
        run: |
          shorebird build apk --split-per-abi

      - name: Upload app-armeabi-v7a-release.apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-armeabi-v7a-release.apk                           
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          releaseNotes: "app-armeabi-v7a-release.apk"
