name: Build and Distribute APKs
on:
  push:
    branches:
      - dev
jobs:
  build_and_distribute:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
      - name: التحقق من الكود
        uses: actions/checkout@v4

      - name: إعداد JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: إعداد فلاتر
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: stable

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: تحميل التبعيات
        run: flutter pub get

      - name: تنظيف المشروع
        run: flutter clean

      - name: بناء نسخ الاندرويد
        run: flutter build apk --split-per-abi

      - name: 🔥 تثبيت Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: 🔑 تسجيل الدخول إلى Firebase
        run: echo '${{ secrets.CREDENTIAL_FILE_CONTENT }}' > firebase-credentials.json

      - name: 🗑️ حذف الإصدارات القديمة من Firebase
        run: |
          firebase appdistribution:releases:list --app ${{ secrets.FIREBASE_APP_ID }} --token "$(firebase login:ci --json < firebase-credentials.json)" | \
          jq -r '.releases[].releaseId' | \
          xargs -I {} firebase appdistribution:releases:delete --app ${{ secrets.FIREBASE_APP_ID }} --release {} --token "$(firebase login:ci --json < firebase-credentials.json)"

      - name: 🚀 توزيع armeabi-v7a
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: armeabi-v7a
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          releaseNotes: "armeabi-v7a build & distributed"

      - name: 🚀 توزيع arm64-v8a
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: arm64-v8a
          file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          releaseNotes: "arm64-v8a build & distributed"
