name: Flutter Integration Tests

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      # 1. إعداد Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
      # 2. تثبيت الحزم
      - name: Install dependencies
        run: flutter pub get
      # 3. تشغيل الاختبارات باستخدام xvfb
      - name: Run integration tests
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx
          xvfb-run -s "-screen 0 1920x1080x24" flutter test integration_test/

      # 4. رفع الصور كـ artifacts
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshots
          path: test_screenshots/
