name: Integration Tests with Android Emulator

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # تثبيت الأدوات الأساسية
      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip lib32stdc++6 lib32z1

      # إعداد Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64

      # إعداد Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: stable

      # إعداد محاكي Android
      - name: Launch Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Pixel_4
          emulator-options: "-no-boot-anim -no-window -gpu swiftshader_indirect"
          disable-linux-hw-accel: true
          disable-animations: true

      # التحقق من الأجهزة المتصلة
      - name: List connected devices
        run: adb devices

      # تشغيل اختبارات Flutter
      - name: Run Flutter integration tests
        run: flutter test integration_test/app_test.dart
