name: Integration Tests

on:
  push:
    branches:
      - dev  # تشغيل الخطوات عند التحديث على فرع dev
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #! 1. تثبيت الأدوات الأساسية
      - name: Install basic tools
        run: sudo apt-get update && sudo apt-get install -y curl git unzip xz-utils

      #! 2. إعداد Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: stable

      #! 3. إعداد محاكي Android
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2  # النسخة الصحيحة
        with:
          api-level: 30              # إصدار API
          target: google_apis        # الهدف: Google APIs
          arch: x86_64               # معمارية المحاكي
          profile: Pixel_4           # اسم المحاكي
          emulator-options: "-no-boot-anim -no-window"

      #! 4. تشغيل المحاكي
      - name: Start Android Emulator
        run: adb devices
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      #! 5. التحقق من الأجهزة المتصلة
      - name: List connected devices
        run: flutter devices

      #! 6. تشغيل اختبارات التكامل
      - name: Run integration tests on Android Emulator
        run: flutter test integration_test/app_test.dart
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-x64
          PUB_CACHE: ${{ runner.temp }}/.pub-cache
