name: Update Screenshots
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install basic tools
        run: sudo apt-get update && sudo apt-get install -y curl git unzip xz-utils xvfb

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: stable

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests
        run: |
          xvfb-run -s "-screen 0 1920x1080x24" flutter test -d linux integration_test/app_test.dart
